"""Initial schema

Revision ID: 2d36fb91aa53
Revises: 
Create Date: 2026-06-25 13:58:35.488965
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2d36fb91aa53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_department_id', sa.UUID(), nullable=True),
    sa.Column('head_officer_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('office_location', sa.String(length=255), nullable=True),
    sa.Column('annual_budget', sa.Float(), nullable=True),
    sa.Column('budget_utilized', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('complaint_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('total_complaints', sa.Integer(), nullable=False),
    sa.Column('resolved_complaints', sa.Integer(), nullable=False),
    sa.Column('total_projects', sa.Integer(), nullable=False),
    sa.Column('active_projects', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], name=op.f('fk_departments_parent_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_created_at'), 'departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_is_deleted'), 'departments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_departments_parent_department_id'), 'departments', ['parent_department_id'], unique=False)
    op.create_index(op.f('ix_departments_status'), 'departments', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('COMMISSIONER', 'ENGINEER', 'COORDINATOR', 'CITIZEN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('ward_number', sa.String(length=20), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_login_at', sa.String(length=50), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.String(length=50), nullable=True),
    sa.Column('password_changed_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_ward_number'), 'users', ['ward_number'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_actor_action', 'audit_logs', ['actor_id', 'action'], unique=False)
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('ward_number', sa.String(length=20), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('ai_predicted_category', sa.String(length=50), nullable=True),
    sa.Column('ai_predicted_priority', sa.String(length=20), nullable=True),
    sa.Column('ai_predicted_resolution_days', sa.Integer(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_cluster_id', sa.Integer(), nullable=True),
    sa.Column('ai_processed', sa.Boolean(), nullable=False),
    sa.Column('ai_override', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.String(length=50), nullable=True),
    sa.Column('actual_resolution_days', sa.Integer(), nullable=True),
    sa.Column('sla_due_at', sa.String(length=50), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('citizen_rating', sa.Integer(), nullable=True),
    sa.Column('citizen_feedback', sa.Text(), nullable=True),
    sa.Column('feedback_submitted_at', sa.String(length=50), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.String(length=50), nullable=True),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], name=op.f('fk_complaints_assigned_officer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], name=op.f('fk_complaints_citizen_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_complaints_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['complaints.id'], name=op.f('fk_complaints_duplicate_of_id_complaints'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index(op.f('ix_complaints_ai_cluster_id'), 'complaints', ['ai_cluster_id'], unique=False)
    op.create_index(op.f('ix_complaints_assigned_officer_id'), 'complaints', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_citizen_id'), 'complaints', ['citizen_id'], unique=False)
    op.create_index('ix_complaints_citizen_status', 'complaints', ['citizen_id', 'status'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_number'), 'complaints', ['complaint_number'], unique=True)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_department_id'), 'complaints', ['department_id'], unique=False)
    op.create_index('ix_complaints_department_status', 'complaints', ['department_id', 'status'], unique=False)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_is_deleted'), 'complaints', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_complaints_pin_code'), 'complaints', ['pin_code'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_sla_breached'), 'complaints', ['sla_breached'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index('ix_complaints_status_priority', 'complaints', ['status', 'priority'], unique=False)
    op.create_index('ix_complaints_ward_category', 'complaints', ['ward_number', 'category'], unique=False)
    op.create_index(op.f('ix_complaints_ward_number'), 'complaints', ['ward_number'], unique=False)
    op.create_index(op.f('ix_complaints_zone'), 'complaints', ['zone'], unique=False)
    op.create_table('forum_threads',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_announcement', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_activity_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_forum_threads_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_forum_threads_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_threads'))
    )
    op.create_index(op.f('ix_forum_threads_author_id'), 'forum_threads', ['author_id'], unique=False)
    op.create_index(op.f('ix_forum_threads_category'), 'forum_threads', ['category'], unique=False)
    op.create_index(op.f('ix_forum_threads_created_at'), 'forum_threads', ['created_at'], unique=False)
    op.create_index(op.f('ix_forum_threads_department_id'), 'forum_threads', ['department_id'], unique=False)
    op.create_index('ix_forum_threads_dept_pinned', 'forum_threads', ['department_id', 'is_pinned'], unique=False)
    op.create_index(op.f('ix_forum_threads_id'), 'forum_threads', ['id'], unique=False)
    op.create_index(op.f('ix_forum_threads_is_deleted'), 'forum_threads', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_forum_threads_is_pinned'), 'forum_threads', ['is_pinned'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('projects',
    sa.Column('project_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('planned_start_date', sa.String(length=30), nullable=True),
    sa.Column('planned_end_date', sa.String(length=30), nullable=True),
    sa.Column('actual_start_date', sa.String(length=30), nullable=True),
    sa.Column('actual_end_date', sa.String(length=30), nullable=True),
    sa.Column('last_inspection_date', sa.String(length=30), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('approved_budget', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('budget_utilized_pct', sa.Float(), nullable=False),
    sa.Column('ward_number', sa.String(length=20), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geojson_geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('project_manager_id', sa.UUID(), nullable=True),
    sa.Column('contractor_name', sa.String(length=255), nullable=True),
    sa.Column('contractor_contact', sa.String(length=100), nullable=True),
    sa.Column('delay_probability', sa.Float(), nullable=True),
    sa.Column('overrun_probability', sa.Float(), nullable=True),
    sa.Column('expected_overrun_amount', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_category', sa.String(length=20), nullable=True),
    sa.Column('ai_last_assessed', sa.String(length=50), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_fund', sa.String(length=100), nullable=True),
    sa.Column('tender_number', sa.String(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_projects_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_manager_id'], ['users.id'], name=op.f('fk_projects_project_manager_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_department_id'), 'projects', ['department_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_planned_end_date'), 'projects', ['planned_end_date'], unique=False)
    op.create_index(op.f('ix_projects_project_manager_id'), 'projects', ['project_manager_id'], unique=False)
    op.create_index(op.f('ix_projects_project_number'), 'projects', ['project_number'], unique=True)
    op.create_index(op.f('ix_projects_risk_score'), 'projects', ['risk_score'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index('ix_projects_status_dept', 'projects', ['status', 'department_id'], unique=False)
    op.create_index(op.f('ix_projects_ward_number'), 'projects', ['ward_number'], unique=False)
    op.create_index('ix_projects_ward_status', 'projects', ['ward_number', 'status'], unique=False)
    op.create_index(op.f('ix_projects_zone'), 'projects', ['zone'], unique=False)
    op.create_table('complaint_history',
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('previous_priority', sa.String(length=20), nullable=True),
    sa.Column('new_priority', sa.String(length=20), nullable=True),
    sa.Column('previous_officer_id', sa.String(length=50), nullable=True),
    sa.Column('new_officer_id', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_complaint_history_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_history_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_history'))
    )
    op.create_index(op.f('ix_complaint_history_action'), 'complaint_history', ['action'], unique=False)
    op.create_index(op.f('ix_complaint_history_complaint_id'), 'complaint_history', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_history_created_at'), 'complaint_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaint_history_id'), 'complaint_history', ['id'], unique=False)
    op.create_index(op.f('ix_complaint_history_is_deleted'), 'complaint_history', ['is_deleted'], unique=False)
    op.create_table('forum_comments',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('is_solution', sa.Boolean(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_forum_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['forum_comments.id'], name=op.f('fk_forum_comments_parent_comment_id_forum_comments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], name=op.f('fk_forum_comments_thread_id_forum_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_comments'))
    )
    op.create_index(op.f('ix_forum_comments_author_id'), 'forum_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_forum_comments_created_at'), 'forum_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_forum_comments_id'), 'forum_comments', ['id'], unique=False)
    op.create_index(op.f('ix_forum_comments_is_deleted'), 'forum_comments', ['is_deleted'], unique=False)
    op.create_index('ix_forum_comments_thread', 'forum_comments', ['thread_id'], unique=False)
    op.create_index(op.f('ix_forum_comments_thread_id'), 'forum_comments', ['thread_id'], unique=False)

    # ### end Alembic commands ###

    op.create_foreign_key(
        op.f("fk_departments_head_officer_id_users"),
        "departments",
        "users",
        ["head_officer_id"],
        ["id"],
        ondelete="SET NULL",
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_comments_thread_id'), table_name='forum_comments')
    op.drop_index('ix_forum_comments_thread', table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_is_deleted'), table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_id'), table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_created_at'), table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_author_id'), table_name='forum_comments')
    op.drop_table('forum_comments')
    op.drop_index(op.f('ix_complaint_history_is_deleted'), table_name='complaint_history')
    op.drop_index(op.f('ix_complaint_history_id'), table_name='complaint_history')
    op.drop_index(op.f('ix_complaint_history_created_at'), table_name='complaint_history')
    op.drop_index(op.f('ix_complaint_history_complaint_id'), table_name='complaint_history')
    op.drop_index(op.f('ix_complaint_history_action'), table_name='complaint_history')
    op.drop_table('complaint_history')
    op.drop_index(op.f('ix_projects_zone'), table_name='projects')
    op.drop_index('ix_projects_ward_status', table_name='projects')
    op.drop_index(op.f('ix_projects_ward_number'), table_name='projects')
    op.drop_index('ix_projects_status_dept', table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_risk_score'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_number'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_manager_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_planned_end_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_department_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_forum_threads_is_pinned'), table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_is_deleted'), table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_id'), table_name='forum_threads')
    op.drop_index('ix_forum_threads_dept_pinned', table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_department_id'), table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_created_at'), table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_category'), table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_author_id'), table_name='forum_threads')
    op.drop_table('forum_threads')
    op.drop_index(op.f('ix_complaints_zone'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_ward_number'), table_name='complaints')
    op.drop_index('ix_complaints_ward_category', table_name='complaints')
    op.drop_index('ix_complaints_status_priority', table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_sla_breached'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_pin_code'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_is_deleted'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index('ix_complaints_department_status', table_name='complaints')
    op.drop_index(op.f('ix_complaints_department_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_number'), table_name='complaints')
    op.drop_index('ix_complaints_citizen_status', table_name='complaints')
    op.drop_index(op.f('ix_complaints_citizen_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_officer_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_ai_cluster_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_index('ix_audit_actor_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_ward_number'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_status'), table_name='departments')
    op.drop_index(op.f('ix_departments_parent_department_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_deleted'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_created_at'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
